doctrine:
  dbal:
    default_connection: pgsql
    connections:
      pgsql:
        url: 'pgsql://symfony:111@127.0.0.1:5432/lsi'
        driver: 'pdo_pgsql'
        server_version: '9.3'
  orm:
    default_entity_manager: pgsql
    entity_managers:
      pgsql:
        connection: pgsql
        mappings:
          pgsql:
            is_bundle: false
            type: annotation
            prefix: 'App\Entity'
            alias: pgsql
            dir: '%kernel.project_dir%/src/Entity'
